-- Convert all primary keys and foreign keys from TEXT to native PostgreSQL UUID.
-- Drop FKs first, alter columns, then recreate FKs with the same rules.

-- DropForeignKey
ALTER TABLE "User" DROP CONSTRAINT "User_branchId_fkey";
ALTER TABLE "Student" DROP CONSTRAINT "Student_createdById_fkey";
ALTER TABLE "StudentLog" DROP CONSTRAINT "StudentLog_createdById_fkey";
ALTER TABLE "StudentLog" DROP CONSTRAINT "StudentLog_studentId_fkey";
ALTER TABLE "Product" DROP CONSTRAINT "Product_teacherId_fkey";
ALTER TABLE "Product" DROP CONSTRAINT "Product_studyYearId_fkey";
ALTER TABLE "Product" DROP CONSTRAINT "Product_academicYearId_fkey";
ALTER TABLE "Inventory" DROP CONSTRAINT "Inventory_branchId_fkey";
ALTER TABLE "Inventory" DROP CONSTRAINT "Inventory_productId_fkey";
ALTER TABLE "StockMovement" DROP CONSTRAINT "StockMovement_branchId_fkey";
ALTER TABLE "StockMovement" DROP CONSTRAINT "StockMovement_productId_fkey";
ALTER TABLE "StockMovement" DROP CONSTRAINT "StockMovement_createdById_fkey";
ALTER TABLE "Sale" DROP CONSTRAINT "Sale_studentId_fkey";
ALTER TABLE "Sale" DROP CONSTRAINT "Sale_branchId_fkey";
ALTER TABLE "Sale" DROP CONSTRAINT "Sale_createdById_fkey";
ALTER TABLE "Sale" DROP CONSTRAINT "Sale_reservationId_fkey";
ALTER TABLE "SaleItem" DROP CONSTRAINT "SaleItem_saleId_fkey";
ALTER TABLE "SaleItem" DROP CONSTRAINT "SaleItem_productId_fkey";
ALTER TABLE "Reservation" DROP CONSTRAINT "Reservation_studentId_fkey";
ALTER TABLE "Reservation" DROP CONSTRAINT "Reservation_branchId_fkey";
ALTER TABLE "Reservation" DROP CONSTRAINT "Reservation_productId_fkey";
ALTER TABLE "Reservation" DROP CONSTRAINT "Reservation_createdById_fkey";
ALTER TABLE "Payment" DROP CONSTRAINT "Payment_saleId_fkey";
ALTER TABLE "Payment" DROP CONSTRAINT "Payment_reservationId_fkey";
ALTER TABLE "Payment" DROP CONSTRAINT "Payment_createdById_fkey";
ALTER TABLE "returns" DROP CONSTRAINT "returns_saleId_fkey";
ALTER TABLE "returns" DROP CONSTRAINT "returns_createdById_fkey";
ALTER TABLE "ReturnItem" DROP CONSTRAINT "ReturnItem_returnId_fkey";
ALTER TABLE "ReturnItem" DROP CONSTRAINT "ReturnItem_saleItemId_fkey";
ALTER TABLE "Refund" DROP CONSTRAINT "Refund_saleId_fkey";
ALTER TABLE "Refund" DROP CONSTRAINT "Refund_reservationId_fkey";
ALTER TABLE "Refund" DROP CONSTRAINT "Refund_returnId_fkey";
ALTER TABLE "Refund" DROP CONSTRAINT "Refund_exchangeId_fkey";
ALTER TABLE "Refund" DROP CONSTRAINT "Refund_createdById_fkey";
ALTER TABLE "Exchange" DROP CONSTRAINT "Exchange_saleId_fkey";
ALTER TABLE "Exchange" DROP CONSTRAINT "Exchange_saleItemId_fkey";
ALTER TABLE "Exchange" DROP CONSTRAINT "Exchange_newProductId_fkey";
ALTER TABLE "Exchange" DROP CONSTRAINT "Exchange_createdById_fkey";
ALTER TABLE "Expense" DROP CONSTRAINT "Expense_categoryId_fkey";
ALTER TABLE "Expense" DROP CONSTRAINT "Expense_branchId_fkey";
ALTER TABLE "Expense" DROP CONSTRAINT "Expense_createdById_fkey";

-- AlterTable: primary keys
ALTER TABLE "User" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "Branch" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "Teacher" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "StudyYear" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "AcademicYear" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "Student" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "StudentLog" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "Product" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "Inventory" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "StockMovement" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "Sale" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "SaleItem" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "Reservation" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "Payment" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "returns" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "ReturnItem" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "Refund" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "Exchange" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "ExpenseCategory" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;
ALTER TABLE "Expense" ALTER COLUMN "id" SET DATA TYPE UUID USING "id"::uuid;

-- AlterTable: foreign keys
ALTER TABLE "User" ALTER COLUMN "branchId" SET DATA TYPE UUID USING "branchId"::uuid;
ALTER TABLE "Student" ALTER COLUMN "createdById" SET DATA TYPE UUID USING "createdById"::uuid;
ALTER TABLE "StudentLog" ALTER COLUMN "studentId" SET DATA TYPE UUID USING "studentId"::uuid;
ALTER TABLE "StudentLog" ALTER COLUMN "createdById" SET DATA TYPE UUID USING "createdById"::uuid;
ALTER TABLE "Product" ALTER COLUMN "teacherId" SET DATA TYPE UUID USING "teacherId"::uuid;
ALTER TABLE "Product" ALTER COLUMN "studyYearId" SET DATA TYPE UUID USING "studyYearId"::uuid;
ALTER TABLE "Product" ALTER COLUMN "academicYearId" SET DATA TYPE UUID USING "academicYearId"::uuid;
ALTER TABLE "Inventory" ALTER COLUMN "branchId" SET DATA TYPE UUID USING "branchId"::uuid;
ALTER TABLE "Inventory" ALTER COLUMN "productId" SET DATA TYPE UUID USING "productId"::uuid;
ALTER TABLE "StockMovement" ALTER COLUMN "branchId" SET DATA TYPE UUID USING "branchId"::uuid;
ALTER TABLE "StockMovement" ALTER COLUMN "productId" SET DATA TYPE UUID USING "productId"::uuid;
ALTER TABLE "StockMovement" ALTER COLUMN "createdById" SET DATA TYPE UUID USING "createdById"::uuid;
ALTER TABLE "Sale" ALTER COLUMN "studentId" SET DATA TYPE UUID USING "studentId"::uuid;
ALTER TABLE "Sale" ALTER COLUMN "branchId" SET DATA TYPE UUID USING "branchId"::uuid;
ALTER TABLE "Sale" ALTER COLUMN "createdById" SET DATA TYPE UUID USING "createdById"::uuid;
ALTER TABLE "Sale" ALTER COLUMN "reservationId" SET DATA TYPE UUID USING "reservationId"::uuid;
ALTER TABLE "SaleItem" ALTER COLUMN "saleId" SET DATA TYPE UUID USING "saleId"::uuid;
ALTER TABLE "SaleItem" ALTER COLUMN "productId" SET DATA TYPE UUID USING "productId"::uuid;
ALTER TABLE "Reservation" ALTER COLUMN "studentId" SET DATA TYPE UUID USING "studentId"::uuid;
ALTER TABLE "Reservation" ALTER COLUMN "branchId" SET DATA TYPE UUID USING "branchId"::uuid;
ALTER TABLE "Reservation" ALTER COLUMN "productId" SET DATA TYPE UUID USING "productId"::uuid;
ALTER TABLE "Reservation" ALTER COLUMN "createdById" SET DATA TYPE UUID USING "createdById"::uuid;
ALTER TABLE "Payment" ALTER COLUMN "saleId" SET DATA TYPE UUID USING "saleId"::uuid;
ALTER TABLE "Payment" ALTER COLUMN "reservationId" SET DATA TYPE UUID USING "reservationId"::uuid;
ALTER TABLE "Payment" ALTER COLUMN "createdById" SET DATA TYPE UUID USING "createdById"::uuid;
ALTER TABLE "returns" ALTER COLUMN "saleId" SET DATA TYPE UUID USING "saleId"::uuid;
ALTER TABLE "returns" ALTER COLUMN "createdById" SET DATA TYPE UUID USING "createdById"::uuid;
ALTER TABLE "ReturnItem" ALTER COLUMN "returnId" SET DATA TYPE UUID USING "returnId"::uuid;
ALTER TABLE "ReturnItem" ALTER COLUMN "saleItemId" SET DATA TYPE UUID USING "saleItemId"::uuid;
ALTER TABLE "Refund" ALTER COLUMN "saleId" SET DATA TYPE UUID USING "saleId"::uuid;
ALTER TABLE "Refund" ALTER COLUMN "reservationId" SET DATA TYPE UUID USING "reservationId"::uuid;
ALTER TABLE "Refund" ALTER COLUMN "returnId" SET DATA TYPE UUID USING "returnId"::uuid;
ALTER TABLE "Refund" ALTER COLUMN "exchangeId" SET DATA TYPE UUID USING "exchangeId"::uuid;
ALTER TABLE "Refund" ALTER COLUMN "createdById" SET DATA TYPE UUID USING "createdById"::uuid;
ALTER TABLE "Exchange" ALTER COLUMN "saleId" SET DATA TYPE UUID USING "saleId"::uuid;
ALTER TABLE "Exchange" ALTER COLUMN "saleItemId" SET DATA TYPE UUID USING "saleItemId"::uuid;
ALTER TABLE "Exchange" ALTER COLUMN "newProductId" SET DATA TYPE UUID USING "newProductId"::uuid;
ALTER TABLE "Exchange" ALTER COLUMN "createdById" SET DATA TYPE UUID USING "createdById"::uuid;
ALTER TABLE "Expense" ALTER COLUMN "categoryId" SET DATA TYPE UUID USING "categoryId"::uuid;
ALTER TABLE "Expense" ALTER COLUMN "branchId" SET DATA TYPE UUID USING "branchId"::uuid;
ALTER TABLE "Expense" ALTER COLUMN "createdById" SET DATA TYPE UUID USING "createdById"::uuid;

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Student" ADD CONSTRAINT "Student_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "StudentLog" ADD CONSTRAINT "StudentLog_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StudentLog" ADD CONSTRAINT "StudentLog_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Product" ADD CONSTRAINT "Product_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "Teacher"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Product" ADD CONSTRAINT "Product_studyYearId_fkey" FOREIGN KEY ("studyYearId") REFERENCES "StudyYear"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Product" ADD CONSTRAINT "Product_academicYearId_fkey" FOREIGN KEY ("academicYearId") REFERENCES "AcademicYear"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Inventory" ADD CONSTRAINT "Inventory_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Inventory" ADD CONSTRAINT "Inventory_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_reservationId_fkey" FOREIGN KEY ("reservationId") REFERENCES "Reservation"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SaleItem" ADD CONSTRAINT "SaleItem_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "Sale"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SaleItem" ADD CONSTRAINT "SaleItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "Sale"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_reservationId_fkey" FOREIGN KEY ("reservationId") REFERENCES "Reservation"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "returns" ADD CONSTRAINT "returns_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "Sale"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "returns" ADD CONSTRAINT "returns_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ReturnItem" ADD CONSTRAINT "ReturnItem_returnId_fkey" FOREIGN KEY ("returnId") REFERENCES "returns"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ReturnItem" ADD CONSTRAINT "ReturnItem_saleItemId_fkey" FOREIGN KEY ("saleItemId") REFERENCES "SaleItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "Sale"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_reservationId_fkey" FOREIGN KEY ("reservationId") REFERENCES "Reservation"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_returnId_fkey" FOREIGN KEY ("returnId") REFERENCES "returns"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_exchangeId_fkey" FOREIGN KEY ("exchangeId") REFERENCES "Exchange"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Refund" ADD CONSTRAINT "Refund_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Exchange" ADD CONSTRAINT "Exchange_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "Sale"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Exchange" ADD CONSTRAINT "Exchange_saleItemId_fkey" FOREIGN KEY ("saleItemId") REFERENCES "SaleItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Exchange" ADD CONSTRAINT "Exchange_newProductId_fkey" FOREIGN KEY ("newProductId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Exchange" ADD CONSTRAINT "Exchange_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "ExpenseCategory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
